using System; using System.Drawing; using System.IO; using System.Linq; using System.Management; using System.Reflection; using System.Runtime.InteropServices; using System.Windows.Forms;
[assembly: AssemblyTitle("OMEN Lite Control")]
[assembly: AssemblyDescription("Lightweight controls for HP OMEN 15-dc0xxx (84DB)")]
[assembly: AssemblyVersion("0.1.0.0")]
[assembly: AssemblyFileVersion("0.1.0.0")]
[assembly: AssemblyInformationalVersion("0.1.0-beta")]
namespace OmenModeSwitcher {
 static class HpBios {
  static ManagementObject Bios(){var s=new ManagementScope(@"root\wmi");s.Connect();var q=new ObjectQuery("SELECT * FROM hpqBIntM");var all=new ManagementObjectSearcher(s,q).Get().Cast<ManagementObject>().ToArray();var b=all.FirstOrDefault(x=>String.Equals(Convert.ToString(x["InstanceName"]),@"ACPI\PNP0C14\0_0",StringComparison.OrdinalIgnoreCase))??all.FirstOrDefault();if(b==null)throw new InvalidOperationException("找不到 HP WMI BIOS 接口。");return b;}
  static ManagementBaseObject Call(string method,uint cmd,uint type,byte[] data){using(var b=Bios()){var dc=new ManagementClass(b.Scope,new ManagementPath("hpqBDataIn"),null);var i=dc.CreateInstance();i["Sign"]=new byte[]{0x53,0x45,0x43,0x55};i["Command"]=cmd;i["CommandType"]=type;i["Size"]=(uint)data.Length;i["hpqBData"]=data;var p=b.GetMethodParameters(method);p["InData"]=i;var r=b.InvokeMethod(method,p,null);var o=r["OutData"] as ManagementBaseObject;if(o==null)throw new InvalidOperationException("BIOS 没有返回结果。");int c=Convert.ToInt32(o["rwReturnCode"]);if(c!=0)throw new InvalidOperationException("BIOS 返回错误码 "+c+"。");return o;}}
  public static void SetMode(byte m){Call("hpqBIOSInt0",0x20008,0x1A,new byte[]{0xFF,m,0,0});}
  public static byte[] GetColors(){var d=Call("hpqBIOSInt128",0x20009,0x02,new byte[]{0,0,0,0})["Data"] as byte[];if(d==null||d.Length!=128)throw new InvalidOperationException("键盘色表长度不正确。");return d;}
  public static void SetZones(Color[] colors,int[] brightness){byte[] d=GetColors();int n=Math.Min((int)d[0]+1,4);if(n<1)throw new InvalidOperationException("没有可用的键盘分区。");if(colors==null||brightness==null||colors.Length<n||brightness.Length<n)throw new ArgumentException("分区颜色参数不完整。");string f=Path.Combine(AppDomain.CurrentDomain.BaseDirectory,"keyboard-color-backup.bin");if(!File.Exists(f))File.WriteAllBytes(f,d);for(int x=0;x<n;x++){int p=25+x*3,b=Math.Max(0,Math.Min(100,brightness[x]));d[p]=(byte)Math.Round(colors[x].R*b/100.0);d[p+1]=(byte)Math.Round(colors[x].G*b/100.0);d[p+2]=(byte)Math.Round(colors[x].B*b/100.0);}Call("hpqBIOSInt0",0x20009,0x03,d);}
 }
 static class CpuBoost {
  static readonly Guid Processor=new Guid("54533251-82be-4824-96c1-47b60b740d00"),Boost=new Guid("be337238-0d82-4146-a960-4f3749d470c7");
  [DllImport("powrprof.dll")]static extern uint PowerGetActiveScheme(IntPtr root,out IntPtr scheme);
  [DllImport("powrprof.dll")]static extern uint PowerReadACValueIndex(IntPtr root,ref Guid scheme,ref Guid subgroup,ref Guid setting,out uint value);
  [DllImport("powrprof.dll")]static extern uint PowerReadDCValueIndex(IntPtr root,ref Guid scheme,ref Guid subgroup,ref Guid setting,out uint value);
  [DllImport("powrprof.dll")]static extern uint PowerWriteACValueIndex(IntPtr root,ref Guid scheme,ref Guid subgroup,ref Guid setting,uint value);
  [DllImport("powrprof.dll")]static extern uint PowerWriteDCValueIndex(IntPtr root,ref Guid scheme,ref Guid subgroup,ref Guid setting,uint value);
  [DllImport("powrprof.dll")]static extern uint PowerSetActiveScheme(IntPtr root,ref Guid scheme);
  [DllImport("kernel32.dll")]static extern IntPtr LocalFree(IntPtr mem);
  static string Backup{get{return Path.Combine(AppDomain.CurrentDomain.BaseDirectory,"normal-cpu-boost.txt");}}
  static Guid Active(){IntPtr p;uint r=PowerGetActiveScheme(IntPtr.Zero,out p);if(r!=0)throw new InvalidOperationException("读取活动电源计划失败："+r);try{return (Guid)Marshal.PtrToStructure(p,typeof(Guid));}finally{LocalFree(p);}}
  static uint[] Read(Guid g){Guid sg=Processor,st=Boost;uint ac,dc,r1=PowerReadACValueIndex(IntPtr.Zero,ref g,ref sg,ref st,out ac),r2=PowerReadDCValueIndex(IntPtr.Zero,ref g,ref sg,ref st,out dc);if(r1!=0||r2!=0)throw new InvalidOperationException("读取睿频策略失败："+r1+"/"+r2);return new uint[]{ac,dc};}
  static void Write(Guid g,uint ac,uint dc,bool activate){Guid sg=Processor,st=Boost;uint r1=PowerWriteACValueIndex(IntPtr.Zero,ref g,ref sg,ref st,ac),r2=PowerWriteDCValueIndex(IntPtr.Zero,ref g,ref sg,ref st,dc);if(r1!=0||r2!=0)throw new InvalidOperationException("写入睿频策略失败："+r1+"/"+r2);if(activate){uint r3=PowerSetActiveScheme(IntPtr.Zero,ref g);if(r3!=0)throw new InvalidOperationException("应用睿频策略失败："+r3);}}
  public static string EnterEco(){Guid g=Active();uint[] v=Read(g);if(!File.Exists(Backup))File.WriteAllText(Backup,g+Environment.NewLine+v[0]+Environment.NewLine+v[1]);if(v[0]!=0||v[1]!=0)Write(g,0,0,true);return "，CPU 睿频已禁用（原策略 "+v[0]+"/"+v[1]+"）";}
  public static string LeaveEco(){if(!File.Exists(Backup))return "，CPU 睿频无待恢复项";string[] a=File.ReadAllLines(Backup);Guid g;uint ac,dc;if(a.Length<3||!Guid.TryParse(a[0],out g)||!UInt32.TryParse(a[1],out ac)||!UInt32.TryParse(a[2],out dc))throw new InvalidOperationException("睿频备份文件无效。");Guid current=Active();Write(g,ac,dc,current==g);File.Delete(Backup);return "，CPU 睿频策略已恢复为 "+ac+"/"+dc;}
 }
 static class NvidiaLimiter {
  [DllImport("OmenNvApi.dll",CallingConvention=CallingConvention.Winapi)]static extern int GetMaxFrameRate();
  [DllImport("OmenNvApi.dll",CallingConvention=CallingConvention.Winapi)]static extern int SetMaxFrameRate(int maxFrameRate);
  static string Backup{get{return Path.Combine(AppDomain.CurrentDomain.BaseDirectory,"normal-nvidia-fps.txt");}}
  static int Current(){int n=GetMaxFrameRate();if(n<0)throw new InvalidOperationException("NVIDIA 驱动读取失败："+n);return n<=1023?n:0;}
  static void Set(int n){int r=SetMaxFrameRate(n);if(r!=0)throw new InvalidOperationException("NVIDIA 驱动返回 "+r);}
  public static string EnterEco(){int old=Current();if(!File.Exists(Backup))File.WriteAllText(Backup,old.ToString());int target=old>0&&old<60?old:60;if(old!=target)Set(target);return "，NVIDIA 帧率上限 "+(old==0?"关闭":old.ToString())+" → "+target+" FPS";}
  public static string LeaveEco(){if(!File.Exists(Backup))return "，NVIDIA 帧率无待恢复项";int old;if(!Int32.TryParse(File.ReadAllText(Backup).Trim(),out old)||old<0||old>1023)throw new InvalidOperationException("NVIDIA 帧率备份文件无效。");Set(old);File.Delete(Backup);return "，NVIDIA 帧率上限已恢复为 "+(old==0?"关闭":old+" FPS");}
 }
 static class DisplayRefresh {
  const int ENUM_CURRENT_SETTINGS=-1,DISP_CHANGE_SUCCESSFUL=0;const uint DM_DISPLAYFREQUENCY=0x00400000;
  [StructLayout(LayoutKind.Sequential,CharSet=CharSet.Unicode)]struct DEVMODE{[MarshalAs(UnmanagedType.ByValTStr,SizeConst=32)]public string dmDeviceName;public short dmSpecVersion,dmDriverVersion,dmSize,dmDriverExtra;public int dmFields,dmPositionX,dmPositionY,dmDisplayOrientation,dmDisplayFixedOutput;public short dmColor,dmDuplex,dmYResolution,dmTTOption,dmCollate;[MarshalAs(UnmanagedType.ByValTStr,SizeConst=32)]public string dmFormName;public short dmLogPixels;public int dmBitsPerPel,dmPelsWidth,dmPelsHeight,dmDisplayFlags,dmDisplayFrequency,dmICMMethod,dmICMIntent,dmMediaType,dmDitherType,dmReserved1,dmReserved2,dmPanningWidth,dmPanningHeight;}
  [DllImport("user32.dll",CharSet=CharSet.Unicode)]static extern bool EnumDisplaySettings(string deviceName,int modeNum,ref DEVMODE devMode);
  [DllImport("user32.dll",CharSet=CharSet.Unicode)]static extern int ChangeDisplaySettings(ref DEVMODE devMode,uint flags);
  static DEVMODE NewMode(){var d=new DEVMODE();d.dmSize=(short)Marshal.SizeOf(typeof(DEVMODE));return d;}
  static string Backup{get{return Path.Combine(AppDomain.CurrentDomain.BaseDirectory,"normal-refresh-rate.txt");}}
  public static int Current(){var d=NewMode();if(!EnumDisplaySettings(null,ENUM_CURRENT_SETTINGS,ref d))throw new InvalidOperationException("无法读取当前刷新率。");return d.dmDisplayFrequency;}
  static int Closest(int target,int w,int h,int tolerance){int best=-1,diff=Int32.MaxValue;for(int i=0;;i++){var d=NewMode();if(!EnumDisplaySettings(null,i,ref d))break;if(d.dmPelsWidth!=w||d.dmPelsHeight!=h)continue;int x=Math.Abs(d.dmDisplayFrequency-target);if(x<diff){best=d.dmDisplayFrequency;diff=x;}}return diff<=tolerance?best:-1;}
  static int SetClosest(int hz,int tolerance){var d=NewMode();if(!EnumDisplaySettings(null,ENUM_CURRENT_SETTINGS,ref d))throw new InvalidOperationException("无法读取显示模式。");int actual=Closest(hz,d.dmPelsWidth,d.dmPelsHeight,tolerance);if(actual<0)throw new InvalidOperationException("当前分辨率没有接近 "+hz+"Hz 的显示模式。");d.dmFields=(int)DM_DISPLAYFREQUENCY;d.dmDisplayFrequency=actual;int r=ChangeDisplaySettings(ref d,0);if(r!=DISP_CHANGE_SUCCESSFUL)throw new InvalidOperationException("设置 "+actual+"Hz 失败，系统返回 "+r+"。");return actual;}
  public static string EnterEco(){int now=Current();if(!File.Exists(Backup)&&now>61)File.WriteAllText(Backup,now.ToString());int actual=now;if(Math.Abs(now-60)>1)actual=SetClosest(60,1);return "，刷新率 "+now+"Hz → "+actual+"Hz";}
  public static string LeaveEco(){if(!File.Exists(Backup))return "，刷新率保持 "+Current()+"Hz";int target;if(!Int32.TryParse(File.ReadAllText(Backup).Trim(),out target)||target<1)throw new InvalidOperationException("刷新率备份文件无效。");int now=Current(),actual=now;if(now!=target)actual=SetClosest(target,5);File.Delete(Backup);return "，刷新率 "+now+"Hz → "+actual+"Hz";}
 }
 static class StatusReader {
  public static string LocalMode(){string f=Path.Combine(AppDomain.CurrentDomain.BaseDirectory,"last-mode.txt");return File.Exists(f)?File.ReadAllText(f).Trim():"未知（尚未由本工具设置）";}
  public static string Colors(byte[] d){int n=Math.Min((int)d[0]+1,4);string[] z={"右区","中区","左区","WASD"};string[] a=new string[n];for(int i=0;i<n;i++){int p=25+i*3;a[i]=z[i]+" #"+d[p].ToString("X2")+d[p+1].ToString("X2")+d[p+2].ToString("X2");}return string.Join("  ",a);}
 }
 sealed class MainForm:Form {
  Label mode,color,msg,hz;Color[] zoneColors=new Color[4];TrackBar[] zoneBrightness=new TrackBar[4];Button[] zoneButtons=new Button[4];Label[] zonePercent=new Label[4];bool zonesLoaded;
  public MainForm(){Text="OMEN 独立控制器";Font=new Font("Microsoft YaHei UI",9.5F);ClientSize=new Size(650,635);FormBorderStyle=FormBorderStyle.FixedDialog;MaximizeBox=false;StartPosition=FormStartPosition.CenterScreen;var title=L("OMEN 独立性能与键盘控制",20,6,610,48);title.Font=new Font(Font.FontFamily,16F,FontStyle.Bold);L("本工具最后设置：",22,65,175,26);mode=L("正在读取…",200,65,285,26);var refresh=B("刷新状态",518,61,105,32);refresh.Click+=(s,e)=>RefreshAll();L("当前屏幕刷新率：",22,98,175,26);hz=L("正在读取…",200,98,405,26);var mb=G("本机 HP BIOS 性能策略（84DB 专用）",20,135,610,105);var def=B("默认",18,30,135,48,mb);var perf=B("狂暴 / 性能",164,30,135,48,mb);var cool=B("酷冷",310,30,135,48,mb);var eco=B("节能",456,30,135,48,mb);def.Click+=(s,e)=>Mode("默认模式",0,"neutral");perf.Click+=(s,e)=>Mode("狂暴 / 性能模式",1,"performance");cool.Click+=(s,e)=>Mode("酷冷模式",2,"neutral");eco.Click+=(s,e)=>Mode("节能模式",0,"efficiency");var kb=G("键盘四分区静态颜色与亮度（RGB 强度）",20,250,610,305);string[] zn={"右区","中区","左区","WASD"};for(int i=0;i<4;i++){int k=i,y=27+i*47;L(zn[i],15,y,62,32,kb);zoneButtons[i]=B("选择颜色",80,y,115,32,kb);zoneButtons[i].Click+=(s,e)=>PickZone(k);zoneBrightness[i]=new TrackBar{Minimum=0,Maximum=100,TickFrequency=10,Value=100};zoneBrightness[i].SetBounds(210,y-2,285,40);kb.Controls.Add(zoneBrightness[i]);zonePercent[i]=L("100%",505,y,55,32,kb);zoneBrightness[i].ValueChanged+=(s,e)=>zonePercent[k].Text=zoneBrightness[k].Value+"%";}color=L("当前色值：尚未读取",15,207,575,25,kb);var white=B("全部白色",15,244,100,34,kb);var red=B("全部红色",125,244,100,34,kb);var blue=B("全部蓝色",235,244,100,34,kb);var purple=B("全部紫色",345,244,100,34,kb);var apply=B("应用四区",475,240,115,42,kb);white.Click+=(s,e)=>AllColor(Color.White);red.Click+=(s,e)=>AllColor(Color.FromArgb(220,0,0));blue.Click+=(s,e)=>AllColor(Color.FromArgb(0,90,255));purple.Click+=(s,e)=>AllColor(Color.FromArgb(145,30,210));apply.Click+=(s,e)=>ApplyZones();msg=L("完全独立：不加载、不启动、不连接 OMEN Gaming Hub。",20,570,610,50);msg.TextAlign=ContentAlignment.MiddleCenter;RefreshAll();}
  Label L(string t,int x,int y,int w,int h,Control p=null){var l=new Label{Text=t,TextAlign=ContentAlignment.MiddleLeft};l.SetBounds(x,y,w,h);(p??this).Controls.Add(l);return l;}Button B(string t,int x,int y,int w,int h,Control p=null){var b=new Button{Text=t};b.SetBounds(x,y,w,h);(p??this).Controls.Add(b);return b;}GroupBox G(string t,int x,int y,int w,int h){var g=new GroupBox{Text=t};g.SetBounds(x,y,w,h);Controls.Add(g);return g;}
  void RefreshAll(){try{mode.Text=StatusReader.LocalMode();}catch(Exception e){mode.Text="读取失败："+e.Message;}try{hz.Text=DisplayRefresh.Current()+" Hz";}catch(Exception e){hz.Text="读取失败："+e.Message;}try{byte[] d=HpBios.GetColors();color.Text="当前色值："+StatusReader.Colors(d);string f=Path.Combine(AppDomain.CurrentDomain.BaseDirectory,"keyboard-color-backup.bin");if(!File.Exists(f))File.WriteAllBytes(f,d);if(!zonesLoaded){int n=Math.Min((int)d[0]+1,4);for(int i=0;i<4;i++){int p=25+Math.Min(i,Math.Max(0,n-1))*3;zoneColors[i]=Color.FromArgb(d[p],d[p+1],d[p+2]);zoneButtons[i].BackColor=zoneColors[i];zoneButtons[i].ForeColor=zoneColors[i].GetBrightness()<0.45f?Color.White:Color.Black;}zonesLoaded=true;}}catch(Exception e){color.Text="当前色值：读取失败（"+e.Message+"）";}}
  static string TryPart(Func<string> action,string name,out bool ok){try{ok=true;return action();}catch(Exception e){ok=false;return "，"+name+"失败："+e.Message;}}
  void Mode(string n,byte v,string power){try{bool eco=power=="efficiency",a,b,c;HpBios.SetMode(v);string detail="";if(eco){detail+=TryPart(NvidiaLimiter.EnterEco,"NVIDIA 限帧",out a);detail+=TryPart(DisplayRefresh.EnterEco,"刷新率",out b);detail+=TryPart(CpuBoost.EnterEco,"CPU 睿频",out c);}else{detail+=TryPart(NvidiaLimiter.LeaveEco,"NVIDIA 恢复",out a);detail+=TryPart(DisplayRefresh.LeaveEco,"刷新率恢复",out b);detail+=TryPart(CpuBoost.LeaveEco,"CPU 睿频恢复",out c);}File.WriteAllText(Path.Combine(AppDomain.CurrentDomain.BaseDirectory,"last-mode.txt"),n);mode.Text=n;string result="已独立写入“"+n+"”（BIOS 值 "+v+"）"+detail+"。";if(a&&b&&c)Ok(result);else Warn("BIOS 模式已写入，但存在附加操作失败，可再次点击重试："+detail);RefreshAll();}catch(Exception e){Fail(e);}}void PickZone(int i){using(var d=new ColorDialog{Color=zoneColors[i],FullOpen=true})if(d.ShowDialog(this)==DialogResult.OK){zoneColors[i]=d.Color;zoneButtons[i].BackColor=d.Color;zoneButtons[i].ForeColor=d.Color.GetBrightness()<0.45f?Color.White:Color.Black;}}void AllColor(Color c){for(int i=0;i<4;i++){zoneColors[i]=c;zoneButtons[i].BackColor=c;zoneButtons[i].ForeColor=c.GetBrightness()<0.45f?Color.White:Color.Black;}}void ApplyZones(){try{int[] b=zoneBrightness.Select(x=>x.Value).ToArray();HpBios.SetZones(zoneColors,b);Ok("四个分区的颜色和 RGB 亮度已写入 BIOS 色表。");RefreshAll();}catch(Exception e){Fail(e);}}void Ok(string s){msg.ForeColor=Color.DarkGreen;msg.Text=s;}void Warn(string s){msg.ForeColor=Color.DarkOrange;msg.Text=s;}void Fail(Exception e){msg.ForeColor=Color.DarkRed;msg.Text="操作失败："+e.Message;}
 }
 static class Program{[STAThread]static void Main(){Application.EnableVisualStyles();Application.SetCompatibleTextRenderingDefault(false);Application.Run(new MainForm());}}
}
