using System; using System.Collections.Generic; using System.Drawing; using System.IO; using System.Linq; using System.Management; using System.Reflection; using System.Runtime.InteropServices; using System.Text; using System.Windows.Forms;
[assembly: AssemblyTitle("OMEN Lite Control")]
[assembly: AssemblyDescription("Lightweight controls for HP OMEN 15-dc0xxx (84DB)")]
[assembly: AssemblyVersion("0.2.1.0")]
[assembly: AssemblyFileVersion("0.2.1.0")]
[assembly: AssemblyInformationalVersion("0.2.1-beta")]
namespace OmenModeSwitcher {
 static class HpBios {
  static ManagementObject Bios(){var s=new ManagementScope(@"root\wmi");s.Connect();var q=new ObjectQuery("SELECT * FROM hpqBIntM");var all=new ManagementObjectSearcher(s,q).Get().Cast<ManagementObject>().ToArray();var b=all.FirstOrDefault(x=>String.Equals(Convert.ToString(x["InstanceName"]),@"ACPI\PNP0C14\0_0",StringComparison.OrdinalIgnoreCase))??all.FirstOrDefault();if(b==null)throw new InvalidOperationException("找不到 HP WMI BIOS 接口。");return b;}
  static ManagementBaseObject Call(string method,uint cmd,uint type,byte[] data){using(var b=Bios()){var dc=new ManagementClass(b.Scope,new ManagementPath("hpqBDataIn"),null);var i=dc.CreateInstance();i["Sign"]=new byte[]{0x53,0x45,0x43,0x55};i["Command"]=cmd;i["CommandType"]=type;i["Size"]=(uint)data.Length;i["hpqBData"]=data;var p=b.GetMethodParameters(method);p["InData"]=i;var r=b.InvokeMethod(method,p,null);var o=r["OutData"] as ManagementBaseObject;if(o==null)throw new InvalidOperationException("BIOS 没有返回结果。");int c=Convert.ToInt32(o["rwReturnCode"]);if(c!=0)throw new InvalidOperationException("BIOS 返回错误码 "+c+"。");return o;}}
  public static void SetMode(byte m){Call("hpqBIOSInt0",0x20008,0x1A,new byte[]{0xFF,m,0,0});}
  public static byte[] GetColors(){var d=Call("hpqBIOSInt128",0x20009,0x02,new byte[]{0,0,0,0})["Data"] as byte[];if(d==null||d.Length!=128)throw new InvalidOperationException("键盘色表长度不正确。");return d;}
  public static void SetZones(Color[] colors,int[] brightness){byte[] d=GetColors();int n=Math.Min((int)d[0]+1,4);if(n<1)throw new InvalidOperationException("没有可用的键盘分区。");if(colors==null||brightness==null||colors.Length<n||brightness.Length<n)throw new ArgumentException("分区颜色参数不完整。");string f=Path.Combine(AppDomain.CurrentDomain.BaseDirectory,"keyboard-color-backup.bin");if(!File.Exists(f))File.WriteAllBytes(f,d);for(int x=0;x<n;x++){int p=25+x*3,b=Math.Max(0,Math.Min(100,brightness[x]));d[p]=(byte)Math.Round(colors[x].R*b/100.0);d[p+1]=(byte)Math.Round(colors[x].G*b/100.0);d[p+2]=(byte)Math.Round(colors[x].B*b/100.0);}Call("hpqBIOSInt0",0x20009,0x03,d);}
 }
 static class CpuBoost {
  static readonly Guid Processor=new Guid("54533251-82be-4824-96c1-47b60b740d00"),Boost=new Guid("be337238-0d82-4146-a960-4f3749d470c7");
  [DllImport("powrprof.dll")]static extern uint PowerGetActiveScheme(IntPtr root,out IntPtr scheme);
  [DllImport("powrprof.dll")]static extern uint PowerReadACValueIndex(IntPtr root,ref Guid scheme,ref Guid subgroup,ref Guid setting,out uint value);
  [DllImport("powrprof.dll")]static extern uint PowerReadDCValueIndex(IntPtr root,ref Guid scheme,ref Guid subgroup,ref Guid setting,out uint value);
  [DllImport("powrprof.dll")]static extern uint PowerWriteACValueIndex(IntPtr root,ref Guid scheme,ref Guid subgroup,ref Guid setting,uint value);
  [DllImport("powrprof.dll")]static extern uint PowerWriteDCValueIndex(IntPtr root,ref Guid scheme,ref Guid subgroup,ref Guid setting,uint value);
  [DllImport("powrprof.dll")]static extern uint PowerSetActiveScheme(IntPtr root,ref Guid scheme);
  [DllImport("kernel32.dll")]static extern IntPtr LocalFree(IntPtr mem);
  static string Backup{get{return Path.Combine(AppDomain.CurrentDomain.BaseDirectory,"normal-cpu-boost.txt");}}
  static Guid Active(){IntPtr p;uint r=PowerGetActiveScheme(IntPtr.Zero,out p);if(r!=0)throw new InvalidOperationException("读取活动电源计划失败："+r);try{return (Guid)Marshal.PtrToStructure(p,typeof(Guid));}finally{LocalFree(p);}}
  static uint[] Read(Guid g){Guid sg=Processor,st=Boost;uint ac,dc,r1=PowerReadACValueIndex(IntPtr.Zero,ref g,ref sg,ref st,out ac),r2=PowerReadDCValueIndex(IntPtr.Zero,ref g,ref sg,ref st,out dc);if(r1!=0||r2!=0)throw new InvalidOperationException("读取睿频策略失败："+r1+"/"+r2);return new uint[]{ac,dc};}
  static void Write(Guid g,uint ac,uint dc,bool activate){Guid sg=Processor,st=Boost;uint r1=PowerWriteACValueIndex(IntPtr.Zero,ref g,ref sg,ref st,ac),r2=PowerWriteDCValueIndex(IntPtr.Zero,ref g,ref sg,ref st,dc);if(r1!=0||r2!=0)throw new InvalidOperationException("写入睿频策略失败："+r1+"/"+r2);if(activate){uint r3=PowerSetActiveScheme(IntPtr.Zero,ref g);if(r3!=0)throw new InvalidOperationException("应用睿频策略失败："+r3);}}
  public static string EnterEco(){Guid g=Active();uint[] v=Read(g);if(!File.Exists(Backup))File.WriteAllText(Backup,g+Environment.NewLine+v[0]+Environment.NewLine+v[1]);if(v[0]!=0||v[1]!=0)Write(g,0,0,true);return "，CPU 睿频已禁用（原策略 "+v[0]+"/"+v[1]+"）";}
  public static string LeaveEco(){if(!File.Exists(Backup))return "，CPU 睿频无待恢复项";string[] a=File.ReadAllLines(Backup);Guid g;uint ac,dc;if(a.Length<3||!Guid.TryParse(a[0],out g)||!UInt32.TryParse(a[1],out ac)||!UInt32.TryParse(a[2],out dc))throw new InvalidOperationException("睿频备份文件无效。");Guid current=Active();Write(g,ac,dc,current==g);File.Delete(Backup);return "，CPU 睿频策略已恢复为 "+ac+"/"+dc;}
 }
 static class NvidiaLimiter {
  [DllImport("OmenNvApi.dll",CallingConvention=CallingConvention.Winapi)]static extern int GetMaxFrameRate();
  [DllImport("OmenNvApi.dll",CallingConvention=CallingConvention.Winapi)]static extern int SetMaxFrameRate(int maxFrameRate);
  static string Backup{get{return Path.Combine(AppDomain.CurrentDomain.BaseDirectory,"normal-nvidia-fps.txt");}}
  static int Current(){int n=GetMaxFrameRate();if(n<0)throw new InvalidOperationException("NVIDIA 驱动读取失败："+n);return n<=1023?n:0;}
  static void Set(int n){int r=SetMaxFrameRate(n);if(r!=0)throw new InvalidOperationException("NVIDIA 驱动返回 "+r);}
  public static string EnterEco(){int old=Current();if(!File.Exists(Backup))File.WriteAllText(Backup,old.ToString());int target=old>0&&old<60?old:60;if(old!=target)Set(target);return "，NVIDIA 帧率上限 "+(old==0?"关闭":old.ToString())+" → "+target+" FPS";}
  public static string LeaveEco(){if(!File.Exists(Backup))return "，NVIDIA 帧率无待恢复项";int old;if(!Int32.TryParse(File.ReadAllText(Backup).Trim(),out old)||old<0||old>1023)throw new InvalidOperationException("NVIDIA 帧率备份文件无效。");Set(old);File.Delete(Backup);return "，NVIDIA 帧率上限已恢复为 "+(old==0?"关闭":old+" FPS");}
 }
 static class DisplayRefresh {
  const int ENUM_CURRENT_SETTINGS=-1,DISP_CHANGE_SUCCESSFUL=0;const uint DM_DISPLAYFREQUENCY=0x00400000;
  [StructLayout(LayoutKind.Sequential,CharSet=CharSet.Unicode)]struct DEVMODE{[MarshalAs(UnmanagedType.ByValTStr,SizeConst=32)]public string dmDeviceName;public short dmSpecVersion,dmDriverVersion,dmSize,dmDriverExtra;public int dmFields,dmPositionX,dmPositionY,dmDisplayOrientation,dmDisplayFixedOutput;public short dmColor,dmDuplex,dmYResolution,dmTTOption,dmCollate;[MarshalAs(UnmanagedType.ByValTStr,SizeConst=32)]public string dmFormName;public short dmLogPixels;public int dmBitsPerPel,dmPelsWidth,dmPelsHeight,dmDisplayFlags,dmDisplayFrequency,dmICMMethod,dmICMIntent,dmMediaType,dmDitherType,dmReserved1,dmReserved2,dmPanningWidth,dmPanningHeight;}
  [DllImport("user32.dll",CharSet=CharSet.Unicode)]static extern bool EnumDisplaySettings(string deviceName,int modeNum,ref DEVMODE devMode);
  [DllImport("user32.dll",CharSet=CharSet.Unicode)]static extern int ChangeDisplaySettings(ref DEVMODE devMode,uint flags);
  static DEVMODE NewMode(){var d=new DEVMODE();d.dmSize=(short)Marshal.SizeOf(typeof(DEVMODE));return d;}
  static string Backup{get{return Path.Combine(AppDomain.CurrentDomain.BaseDirectory,"normal-refresh-rate.txt");}}
  public static int Current(){var d=NewMode();if(!EnumDisplaySettings(null,ENUM_CURRENT_SETTINGS,ref d))throw new InvalidOperationException("无法读取当前刷新率。");return d.dmDisplayFrequency;}
  static int Closest(int target,int w,int h,int tolerance){int best=-1,diff=Int32.MaxValue;for(int i=0;;i++){var d=NewMode();if(!EnumDisplaySettings(null,i,ref d))break;if(d.dmPelsWidth!=w||d.dmPelsHeight!=h)continue;int x=Math.Abs(d.dmDisplayFrequency-target);if(x<diff){best=d.dmDisplayFrequency;diff=x;}}return diff<=tolerance?best:-1;}
  static int SetClosest(int hz,int tolerance){var d=NewMode();if(!EnumDisplaySettings(null,ENUM_CURRENT_SETTINGS,ref d))throw new InvalidOperationException("无法读取显示模式。");int actual=Closest(hz,d.dmPelsWidth,d.dmPelsHeight,tolerance);if(actual<0)throw new InvalidOperationException("当前分辨率没有接近 "+hz+"Hz 的显示模式。");d.dmFields=(int)DM_DISPLAYFREQUENCY;d.dmDisplayFrequency=actual;int r=ChangeDisplaySettings(ref d,0);if(r!=DISP_CHANGE_SUCCESSFUL)throw new InvalidOperationException("设置 "+actual+"Hz 失败，系统返回 "+r+"。");return actual;}
  public static string EnterEco(){int now=Current();if(!File.Exists(Backup)&&now>61)File.WriteAllText(Backup,now.ToString());int actual=now;if(Math.Abs(now-60)>1)actual=SetClosest(60,1);return "，刷新率 "+now+"Hz → "+actual+"Hz";}
  public static string LeaveEco(){if(!File.Exists(Backup))return "，刷新率保持 "+Current()+"Hz";int target;if(!Int32.TryParse(File.ReadAllText(Backup).Trim(),out target)||target<1)throw new InvalidOperationException("刷新率备份文件无效。");int now=Current(),actual=now;if(now!=target)actual=SetClosest(target,5);File.Delete(Backup);return "，刷新率 "+now+"Hz → "+actual+"Hz";}
 }
 static class UserData {
  public static readonly string DirectoryPath=Path.Combine(Environment.GetFolderPath(Environment.SpecialFolder.LocalApplicationData),"OMEN-Lite-Control");
  public static string File(string name){Directory.CreateDirectory(DirectoryPath);return Path.Combine(DirectoryPath,name);}
 }
 sealed class KeyboardPreset {
  public string Name; public Color[] Colors=new Color[4]; public int[] Brightness=new int[4];
  public override string ToString(){return Name;}
 }
 static class PresetStore {
  static string PathName{get{return UserData.File("keyboard-presets.txt");}}
  static string Clean(string s){return (s??"").Replace("|"," ").Replace("\r"," ").Replace("\n"," ").Trim();}
  public static List<KeyboardPreset> Load(){var list=new List<KeyboardPreset>();if(!File.Exists(PathName))return list;foreach(string line in File.ReadAllLines(PathName,Encoding.UTF8)){string[] p=line.Split('|');if(p.Length!=9||String.IsNullOrWhiteSpace(p[0]))continue;var x=new KeyboardPreset{Name=p[0]};bool ok=true;for(int i=0;i<4;i++){int rgb=0,b=0;ok&=Int32.TryParse(p[1+i*2],out rgb)&&Int32.TryParse(p[2+i*2],out b)&&rgb>=0&&rgb<=0xFFFFFF&&b>=0&&b<=100;x.Colors[i]=Color.FromArgb(Math.Max(0,Math.Min(0xFFFFFF,rgb)));x.Brightness[i]=Math.Max(0,Math.Min(100,b));}if(ok&&list.Count<8)list.Add(x);}return list;}
  public static void Save(List<KeyboardPreset> list){var lines=list.Take(8).Select(x=>Clean(x.Name)+"|"+String.Join("|",Enumerable.Range(0,4).SelectMany(i=>new[]{(x.Colors[i].ToArgb()&0xFFFFFF).ToString(),x.Brightness[i].ToString()})));File.WriteAllLines(PathName,lines,Encoding.UTF8);}
 }
 static class StatusReader {
  public static string LocalMode(){string f=Path.Combine(AppDomain.CurrentDomain.BaseDirectory,"last-mode.txt");return File.Exists(f)?File.ReadAllText(f).Trim():"unknown";}
  public static string Colors(byte[] d,string[] z){int n=Math.Min((int)d[0]+1,4);string[] a=new string[n];for(int i=0;i<n;i++){int p=25+i*3;a[i]=z[i]+" #"+d[p].ToString("X2")+d[p+1].ToString("X2")+d[p+2].ToString("X2");}return string.Join("  ",a);}
 }
 sealed class MainForm:Form {
  bool english,zonesLoaded; Label title,lastLabel,refreshLabel,mode,color,msg,hz; GroupBox modeBox,kb; Button refresh,def,perf,cool,eco,white,red,blue,purple,apply,savePreset,deletePreset,language; TextBox presetName; ComboBox presetList;
  Color[] zoneColors=new Color[4]; TrackBar[] zoneBrightness=new TrackBar[4]; Button[] zoneButtons=new Button[4]; Label[] zoneLabels=new Label[4],zonePercent=new Label[4]; List<KeyboardPreset> presets;
  string T(string zh,string en){return english?en:zh;}
  string[] Zones(){return english?new[]{"Right","Middle","Left","WASD"}:new[]{"右区","中区","左区","WASD"};}
  public MainForm(){string lf=UserData.File("language.txt");english=File.Exists(lf)&&File.ReadAllText(lf).Trim()=="en";presets=PresetStore.Load();Font=new Font("Microsoft YaHei UI",9.5F);ClientSize=new Size(650,700);FormBorderStyle=FormBorderStyle.FixedDialog;MaximizeBox=false;StartPosition=FormStartPosition.CenterScreen;
   title=L("",20,6,500,48);title.Font=new Font(Font.FontFamily,16F,FontStyle.Bold);language=B("",535,14,88,30);language.Click+=(s,e)=>SwitchLanguage();lastLabel=L("",22,65,175,26);mode=L("",200,65,285,26);refresh=B("",518,61,105,32);refresh.Click+=(s,e)=>RefreshAll();refreshLabel=L("",22,98,175,26);hz=L("",200,98,405,26);
   modeBox=G("",20,135,610,105);def=B("",18,30,135,48,modeBox);perf=B("",164,30,135,48,modeBox);cool=B("",310,30,135,48,modeBox);eco=B("",456,30,135,48,modeBox);def.Click+=(s,e)=>Mode("balanced",0,"neutral");perf.Click+=(s,e)=>Mode("performance",1,"performance");cool.Click+=(s,e)=>Mode("comfort",2,"neutral");eco.Click+=(s,e)=>Mode("eco",0,"efficiency");
   kb=G("",20,250,610,365);for(int i=0;i<4;i++){int k=i,y=27+i*47;zoneLabels[i]=L("",15,y,62,32,kb);zoneButtons[i]=B("",80,y,115,32,kb);zoneButtons[i].Click+=(s,e)=>PickZone(k);zoneBrightness[i]=new TrackBar{Minimum=0,Maximum=100,TickFrequency=10,Value=100};zoneBrightness[i].SetBounds(210,y-2,285,40);kb.Controls.Add(zoneBrightness[i]);zonePercent[i]=L("100%",505,y,55,32,kb);zoneBrightness[i].ValueChanged+=(s,e)=>zonePercent[k].Text=zoneBrightness[k].Value+"%";}
   color=L("",15,207,575,25,kb);white=B("",15,240,100,34,kb);red=B("",125,240,100,34,kb);blue=B("",235,240,100,34,kb);purple=B("",345,240,100,34,kb);apply=B("",475,236,115,42,kb);white.Click+=(s,e)=>AllColor(Color.White);red.Click+=(s,e)=>AllColor(Color.FromArgb(220,0,0));blue.Click+=(s,e)=>AllColor(Color.FromArgb(0,90,255));purple.Click+=(s,e)=>AllColor(Color.FromArgb(145,30,210));apply.Click+=(s,e)=>ApplyZones();
   presetName=new TextBox();presetName.SetBounds(15,293,140,28);kb.Controls.Add(presetName);presetList=new ComboBox{DropDownStyle=ComboBoxStyle.DropDownList};presetList.SetBounds(165,293,190,28);kb.Controls.Add(presetList);savePreset=B("",365,290,105,34,kb);deletePreset=B("",480,290,110,34,kb);presetList.SelectedIndexChanged+=(s,e)=>ShowPreset();savePreset.Click+=(s,e)=>SavePreset();deletePreset.Click+=(s,e)=>DeletePreset();
   msg=L("",20,630,610,55);msg.TextAlign=ContentAlignment.MiddleCenter;ApplyLanguage();ReloadPresetList();RefreshAll();}
  Label L(string t,int x,int y,int w,int h,Control p=null){var l=new Label{Text=t,TextAlign=ContentAlignment.MiddleLeft};l.SetBounds(x,y,w,h);(p??this).Controls.Add(l);return l;} Button B(string t,int x,int y,int w,int h,Control p=null){var b=new Button{Text=t};b.SetBounds(x,y,w,h);(p??this).Controls.Add(b);return b;} GroupBox G(string t,int x,int y,int w,int h){var g=new GroupBox{Text=t};g.SetBounds(x,y,w,h);Controls.Add(g);return g;}
  void ApplyLanguage(){Text=T("OMEN 独立控制器","OMEN Lite Control");title.Text=T("OMEN 独立性能与键盘控制","OMEN Performance & Lighting Control");language.Text=english?"中文":"English";lastLabel.Text=T("本工具最后设置：","Last setting:");refresh.Text=T("刷新状态","Refresh");refreshLabel.Text=T("当前屏幕刷新率：","Display refresh rate:");modeBox.Text=T("本机 HP BIOS 性能策略（84DB 专用）","HP BIOS Performance Control (84DB only)");def.Text=T("默认","Balanced");perf.Text=T("狂暴 / 性能","Performance");cool.Text=T("酷冷","Comfort");eco.Text=T("节能","Eco");kb.Text=T("键盘四分区静态颜色与亮度（RGB 强度）","4-Zone Keyboard Lighting (static RGB intensity)");string[] z=Zones();for(int i=0;i<4;i++){zoneLabels[i].Text=z[i];zoneButtons[i].Text=T("选择颜色","Choose Color");}white.Text=T("全部白色","All White");red.Text=T("全部红色","All Red");blue.Text=T("全部蓝色","All Blue");purple.Text=T("全部紫色","All Purple");apply.Text=T("应用","Apply");presetName.Text=String.IsNullOrWhiteSpace(presetName.Text)?T("预设名称","Preset name"):presetName.Text;savePreset.Text=T("保存预设","Save Preset");deletePreset.Text=T("删除预设","Delete Preset");msg.Text=T("完全独立：不加载、不启动、不连接 OMEN Gaming Hub。","Independent: OMEN Gaming Hub is not loaded, started or contacted.");RefreshAll();}
  void SwitchLanguage(){english=!english;File.WriteAllText(UserData.File("language.txt"),english?"en":"zh");ApplyLanguage();}
  string ModeName(string id){if(id=="balanced"||id=="默认模式")return T("默认模式","Balanced");if(id=="performance"||id=="狂暴 / 性能模式")return T("狂暴 / 性能模式","Performance");if(id=="comfort"||id=="酷冷模式")return T("酷冷模式","Comfort");if(id=="eco"||id=="节能模式")return T("节能模式","Eco");return T("未知（尚未由本工具设置）","Unknown (not set by this tool)");}
  void RefreshAll(){try{mode.Text=ModeName(StatusReader.LocalMode());}catch(Exception e){mode.Text=T("读取失败：","Read failed: ")+e.Message;}try{hz.Text=DisplayRefresh.Current()+" Hz";}catch(Exception e){hz.Text=T("读取失败：","Read failed: ")+e.Message;}try{byte[] d=HpBios.GetColors();color.Text=T("当前色值：","Current colors: ")+StatusReader.Colors(d,Zones());string f=Path.Combine(AppDomain.CurrentDomain.BaseDirectory,"keyboard-color-backup.bin");if(!File.Exists(f))File.WriteAllBytes(f,d);if(!zonesLoaded){int n=Math.Min((int)d[0]+1,4);for(int i=0;i<4;i++){int p=25+Math.Min(i,Math.Max(0,n-1))*3;zoneColors[i]=Color.FromArgb(d[p],d[p+1],d[p+2]);PaintZone(i);}zonesLoaded=true;}}catch(Exception e){color.Text=T("当前色值：读取失败（","Current colors: read failed (")+e.Message+")";}}
  string TryPart(Func<string> action,string name,out bool ok){try{string result=action();ok=true;return english?"":result;}catch(Exception e){ok=false;return ", "+name+": "+e.Message;}}
  void Mode(string id,byte v,string power){try{bool ecoMode=power=="efficiency",a,b,c;HpBios.SetMode(v);string detail="";if(ecoMode){detail+=TryPart(NvidiaLimiter.EnterEco,T("NVIDIA 限帧失败","NVIDIA limiter failed"),out a);detail+=TryPart(DisplayRefresh.EnterEco,T("刷新率失败","refresh rate failed"),out b);detail+=TryPart(CpuBoost.EnterEco,T("CPU 睿频失败","CPU boost failed"),out c);}else{detail+=TryPart(NvidiaLimiter.LeaveEco,T("NVIDIA 恢复失败","NVIDIA restore failed"),out a);detail+=TryPart(DisplayRefresh.LeaveEco,T("刷新率恢复失败","refresh restore failed"),out b);detail+=TryPart(CpuBoost.LeaveEco,T("CPU 睿频恢复失败","CPU boost restore failed"),out c);}File.WriteAllText(Path.Combine(AppDomain.CurrentDomain.BaseDirectory,"last-mode.txt"),id);mode.Text=ModeName(id);string result=T("已写入“","Applied ")+ModeName(id)+T("”（BIOS 值 "," (BIOS value ")+v+")"+detail;if(a&&b&&c)Ok(result);else Warn(T("BIOS 模式已写入，但存在附加操作失败，可重试：","BIOS mode applied, but additional operations failed; retry: ")+detail);RefreshAll();}catch(Exception e){Fail(e);}}
  void PaintZone(int i){zoneButtons[i].BackColor=zoneColors[i];zoneButtons[i].ForeColor=zoneColors[i].GetBrightness()<0.45f?Color.White:Color.Black;}
  void PickZone(int i){using(var d=new ColorDialog{Color=zoneColors[i],FullOpen=true})if(d.ShowDialog(this)==DialogResult.OK){zoneColors[i]=d.Color;PaintZone(i);}}
  void AllColor(Color c){for(int i=0;i<4;i++){zoneColors[i]=c;PaintZone(i);}}
  void ApplyZones(){try{HpBios.SetZones(zoneColors,zoneBrightness.Select(x=>x.Value).ToArray());Ok(T("四个分区的颜色和亮度已写入 BIOS 色表。","Four-zone colors and brightness were written to the BIOS color table."));RefreshAll();}catch(Exception e){Fail(e);}}
  void ReloadPresetList(){int old=presetList.SelectedIndex;presetList.Items.Clear();foreach(var p in presets)presetList.Items.Add(p);if(presetList.Items.Count>0)presetList.SelectedIndex=Math.Min(Math.Max(old,0),presetList.Items.Count-1);}
  void SavePreset(){string name=presetName.Text.Trim();if(String.IsNullOrWhiteSpace(name)||name=="预设名称"||name=="Preset name"){Warn(T("请输入预设名称。","Enter a preset name."));return;}int index=presets.FindIndex(x=>String.Equals(x.Name,name,StringComparison.OrdinalIgnoreCase));if(index<0&&presets.Count>=8){Warn(T("最多只能保存 8 个预设。","A maximum of 8 presets can be saved."));return;}var p=new KeyboardPreset{Name=name,Colors=zoneColors.ToArray(),Brightness=zoneBrightness.Select(x=>x.Value).ToArray()};if(index>=0)presets[index]=p;else presets.Add(p);PresetStore.Save(presets);ReloadPresetList();presetList.SelectedItem=presets.First(x=>String.Equals(x.Name,name,StringComparison.OrdinalIgnoreCase));Ok(T("预设已保存：","Preset saved: ")+name);}
  void ShowPreset(){var p=presetList.SelectedItem as KeyboardPreset;if(p==null)return;for(int i=0;i<4;i++){zoneColors[i]=p.Colors[i];zoneBrightness[i].Value=p.Brightness[i];PaintZone(i);}presetName.Text=p.Name;msg.ForeColor=SystemColors.ControlText;msg.Text=T("预设已载入到界面，点击“应用”后写入键盘。","Preset loaded into the editor. Click Apply to write it to the keyboard.");}
  void DeletePreset(){var p=presetList.SelectedItem as KeyboardPreset;if(p==null){Warn(T("请先选择一个预设。","Select a preset first."));return;}presets.Remove(p);PresetStore.Save(presets);ReloadPresetList();Ok(T("预设已删除。","Preset deleted."));}
  void Ok(string s){msg.ForeColor=Color.DarkGreen;msg.Text=s;} void Warn(string s){msg.ForeColor=Color.DarkOrange;msg.Text=s;} void Fail(Exception e){msg.ForeColor=Color.DarkRed;msg.Text=T("操作失败：","Operation failed: ")+e.Message;}
 }
 static class Program{[STAThread]static void Main(){Application.EnableVisualStyles();Application.SetCompatibleTextRenderingDefault(false);Application.Run(new MainForm());}}
}
